services:
  - type: web
    name: assistencia-tecnica-m1
    env: docker
    plan: free
    region: ohio
    disk:
      name: assistencia-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_FILE
        value: /app/data/assistenciadb
