-- ============================================================================
-- [Requisito: Dados Iniciais]
-- O sistema inicia sem dados pré-carregados.
-- Os dados são cadastrados manualmente pela interface web durante a operação.
-- ============================================================================
