/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2026-09-25 17:22:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-BR\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Login - Assistência Técnica M1</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary: #3b82f6;\n");
      out.write("            --primary-hover: #2563eb;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        * {\n");
      out.write("            box-sizing: border-box;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 0;\n");
      out.write("            height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            background: linear-gradient(-45deg, #0f172a, #1e293b, #09090b, #171717);\n");
      out.write("            background-size: 400% 400%;\n");
      out.write("            animation: gradientBG 15s ease infinite;\n");
      out.write("            color: #f8fafc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes gradientBG {\n");
      out.write("            0% { background-position: 0% 50%; }\n");
      out.write("            50% { background-position: 100% 50%; }\n");
      out.write("            100% { background-position: 0% 50%; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Elementos decorativos animados de fundo */\n");
      out.write("        .blob {\n");
      out.write("            position: absolute;\n");
      out.write("            filter: blur(80px);\n");
      out.write("            z-index: 0;\n");
      out.write("            opacity: 0.5;\n");
      out.write("            animation: float 10s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("        .blob-1 {\n");
      out.write("            width: 300px;\n");
      out.write("            height: 300px;\n");
      out.write("            background: rgba(59, 130, 246, 0.3);\n");
      out.write("            top: -100px;\n");
      out.write("            left: -100px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("        }\n");
      out.write("        .blob-2 {\n");
      out.write("            width: 400px;\n");
      out.write("            height: 400px;\n");
      out.write("            background: rgba(139, 92, 246, 0.2);\n");
      out.write("            bottom: -150px;\n");
      out.write("            right: -100px;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            animation-delay: -5s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes float {\n");
      out.write("            0% { transform: translateY(0px) scale(1); }\n");
      out.write("            50% { transform: translateY(20px) scale(1.05); }\n");
      out.write("            100% { transform: translateY(0px) scale(1); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-wrapper {\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 1;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 400px;\n");
      out.write("            padding: 0 1.5rem;\n");
      out.write("            animation: slideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes slideUp {\n");
      out.write("            from { opacity: 0; transform: translateY(30px); }\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-card {\n");
      out.write("            background: rgba(15, 23, 42, 0.4);\n");
      out.write("            backdrop-filter: blur(24px);\n");
      out.write("            -webkit-backdrop-filter: blur(24px);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.08);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            padding: 2.5rem 2rem;\n");
      out.write("            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.05) inset;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo-container {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: center;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo-icon {\n");
      out.write("            width: 48px;\n");
      out.write("            height: 48px;\n");
      out.write("            background: linear-gradient(135deg, #3b82f6, #8b5cf6);\n");
      out.write("            border-radius: 12px;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            box-shadow: 0 8px 16px rgba(59, 130, 246, 0.3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .logo-icon svg {\n");
      out.write("            width: 24px;\n");
      out.write("            height: 24px;\n");
      out.write("            color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-title {\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 1.5rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            margin: 0 0 0.5rem 0;\n");
      out.write("            letter-spacing: -0.025em;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-subtitle {\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("            color: #94a3b8;\n");
      out.write("            margin: 0 0 2rem 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-group {\n");
      out.write("            margin-bottom: 1.25rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        label {\n");
      out.write("            display: block;\n");
      out.write("            font-size: 0.875rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("            color: #cbd5e1;\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"email\"], input[type=\"password\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            background: rgba(0, 0, 0, 0.2);\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.1);\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            font-size: 0.9375rem;\n");
      out.write("            color: #f8fafc;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("            font-family: inherit;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input[type=\"email\"]:focus, input[type=\"password\"]:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: var(--primary);\n");
      out.write("            background: rgba(0, 0, 0, 0.3);\n");
      out.write("            box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        input::placeholder {\n");
      out.write("            color: #64748b;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            width: 100%;\n");
      out.write("            background: var(--primary);\n");
      out.write("            color: white;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            font-size: 0.9375rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: var(--primary-hover);\n");
      out.write("            transform: translateY(-1px);\n");
      out.write("            box-shadow: 0 8px 16px rgba(59, 130, 246, 0.25);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:active {\n");
      out.write("            transform: translateY(0);\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"blob blob-1\"></div>\n");
      out.write("    <div class=\"blob blob-2\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"login-wrapper\">\n");
      out.write("        <div class=\"login-card\">\n");
      out.write("            <div class=\"logo-container\">\n");
      out.write("                <div class=\"logo-icon\">\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke-width=\"2\" stroke=\"currentColor\">\n");
      out.write("                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M10.343 3.94c.09-.542.56-.94 1.11-.94h1.093c.55 0 1.02.398 1.11.94l.149.894c.07.424.384.764.78.93.398.164.855.142 1.205-.108l.737-.527a1.125 1.125 0 011.45.12l.773.774c.39.389.44 1.002.12 1.45l-.527.737c-.25.35-.272.806-.107 1.204.165.397.505.71.93.78l.893.15c.543.09.94.56.94 1.109v1.094c0 .55-.397 1.02-.94 1.11l-.893.149c-.425.07-.765.383-.93.78-.165.398-.143.854.107 1.204l.527.738c.32.447.269 1.06-.12 1.45l-.774.773a1.125 1.125 0 01-1.449.12l-.738-.527c-.35-.25-.806-.272-1.203-.107-.397.165-.71.505-.781.929l-.149.894c-.09.542-.56.94-1.11.94h-1.094c-.55 0-1.019-.398-1.11-.94l-.148-.894c-.071-.424-.384-.764-.781-.93-.398-.164-.854-.142-1.204.108l-.738.527c-.447.32-1.06.269-1.45-.12l-.773-.774a1.125 1.125 0 01-.12-1.45l.527-.737c.25-.35.273-.806.108-1.204-.165-.397-.505-.71-.93-.78l-.894-.15c-.542-.09-.94-.56-.94-1.109v-1.094c0-.55.398-1.02.94-1.11l.894-.149c.424-.07.765-.383.93-.78.165-.398.143-.854-.107-1.204l-.527-.738a1.125 1.125 0 01.12-1.45l.773-.773a1.125 1.125 0 011.45-.12l.737.527c.35.25.807.272 1.204.107.397-.165.71-.505.78-.929l.15-.894z\" />\n");
      out.write("                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M15 12a3 3 0 11-6 0 3 3 0 016 0z\" />\n");
      out.write("                    </svg>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <h2 class=\"card-title\">Bem-vindo de volta</h2>\n");
      out.write("            <p class=\"card-subtitle\">Assistência Técnica M1</p>\n");
      out.write("            \n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/controle\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"acao\" value=\"efetuarLogin\">\n");
      out.write("                <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${csrfToken}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"email\">E-mail corporativo</label>\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" required placeholder=\"admin@m1.com\" autofocus>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"senha\">Senha de acesso</label>\n");
      out.write("                    <input type=\"password\" id=\"senha\" name=\"senha\" required placeholder=\"••••••••\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn-primary\">\n");
      out.write("                    Acessar Sistema\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" stroke-width=\"2\">\n");
      out.write("                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" d=\"M14 5l7 7m0 0l-7 7m7-7H3\" />\n");
      out.write("                    </svg>\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
